version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ssafy-yumai:dev
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - FAISS_PATH=${FAISS_PATH}
      - META_PATH=${META_PATH}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload